apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolov8-model
  namespace: safety-monitoring
  labels:
    app: yolov8-model
    tier: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolov8-model
  template:
    metadata:
      labels:
        app: yolov8-model
        tier: model
    spec:
      containers:
      - name: yolov8-model
        image: shrinidhiupadhyaya/code_martians_yolov8-model:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: model-storage
          mountPath: /model
        command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: yolo-model-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: yolov8-model-service
  namespace: safety-monitoring
spec:
  selector:
    app: yolov8-model
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
